### ISSUE TITLE
cloudlet with ”-m“ option goes wrong

### ISSUE THREAD

**Issue by t00197857** [cmusatyalab/elijah-provisioning#6]
thanks for your last reply。In addition，I‘m very intrested in your study。I have succeeded in making such a overlay without “-m“，but with the “-m” option（I want to test free memory ），it went wrong。 I don‘t understand this。 Does this option really support ，or maybe something is wrong with me。（The precise.raw comes from yours）The log is as below：  

tx@tx-HP-Compaq-8200-Elite-MT-PC:~$  cloudlet overlay -m /home/tx/.cloudlet/abda52a61692094b3b7d45c9647d022f5e297d1b788679eb93735374007576b8/precise.raw
INFO     QEMU access file : /tmp/cloudlet-qemu-Dryunx/qemu-trim-log
INFO     start monitoring at /var/tmp/cloudletfs-Xz9fnc/disk/streams/chunks_modified
INFO     start monitoring at /var/tmp/cloudletfs-Xz9fnc/disk/streams/chunks_accessed
INFO     start monitoring at /var/tmp/cloudletfs-Xz9fnc/memory/streams/chunks_accessed
INFO     start monitoring at /tmp/cloudlet-qemu-Dryunx/qemu-trim-log
INFO     * Overlay creation configuration
INFO       - {'DISK_ONLY': False,
 'FREE_SUPPORT': True,
 'TRIM_SUPPORT': True,
 'XRAY_SUPPORT': False,
 'ZIP_CONTAINER': True}
INFO     restoring VM...
INFO     VM is restored...
INFO     waiting for finishing VNC interaction
INFO     stop monitoring at /var/tmp/cloudletfs-Xz9fnc/memory/streams/chunks_accessed
INFO     save VM memory state
DEBUG    start machine save
INFO     Header size of memory snapshot is 8192
[================================================================================>] 100%
DEBUG    finish machine save
WARNING  No TRIM Discard, Check /etc/fstab configuration
INFO     Get memory delta
DEBUG    1.get modified page list
ERROR    failed : reasons - invalid header format: no total memory size, args - {}
ERROR    failed at Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/elijah/provisioning/synthesis.py", line 93, in decorated_function
    return function(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elijah/provisioning/synthesis.py", line 257, in create_overlay
    self.modified_mem.name)
  File "/usr/local/lib/python2.7/dist-packages/elijah/provisioning/synthesis.py", line 839, in get_overlay_deltalist
    free_memory_info=free_memory_dict)
  File "/usr/local/lib/python2.7/dist-packages/elijah/provisioning/memory.py", line 439, in create_memory_deltalist
    free_memory_info=free_memory_info)
  File "/usr/local/lib/python2.7/dist-packages/elijah/provisioning/memory.py", line 365, in get_modified
    apply_free_memory=apply_free_memory)
  File "/usr/local/lib/python2.7/dist-packages/elijah/provisioning/memory.py", line 271, in _load_file
    ram_end_offset, ram_info = Memory._seek_to_end_of_ram(fin)
  File "/usr/local/lib/python2.7/dist-packages/elijah/provisioning/memory.py", line 197, in _seek_to_end_of_ram
    raise MemoryError("invalid header format: no total memory size")
MemoryError: invalid header format: no total memory size

INFO     close Stream monitoring thread
INFO     Fuse close pipe
INFO     NO chunks has been waited at FUSE
INFO     close Fuse Exec thread
INFO     close File monitoring thread
ERROR    Traceback (most recent call last):
  File "/usr/local/bin/cloudlet", line 195, in main
    vm_overlay.create_overlay()
  File "/usr/local/lib/python2.7/dist-packages/elijah/provisioning/synthesis.py", line 102, in decorated_function
    raise 
MemoryError: invalid header format: no total memory size

Failed to create overlay

**Comment by t00197857** [comment]
Besides，I have a question about the issue about  profilng for chunks in order。 “This part (in FUSE file system) tells you disk & memory access order when the VM is launched. Base on this information, you can create your own profiler“. Do you have a specific method about how to create the profiler If the access order information is known by us？Thanks very much。

”
